<a href="https://colab.research.google.com/github/jrpickens/data-science-notebooks/blob/main/5/James_Pickens_04_data_input_output.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

James Pickens

# 📊 04 - Data Input and Output

Most of data science is about **loading data, exploring it, and saving results**.  
In this notebook you will learn:
- Reading CSV files with Pandas
- Inspecting DataFrames (`head`, `info`, `describe`)
- Writing data back to CSV
- Reading Excel files (if available)

## 1. Reading CSV Files

In [ ]:
import pandas as pd

# Create a small CSV for demo
data = """Name,Age,Score
Alice,23,90
Bob,25,85
Charlie,22,95
"""
with open("students.csv", "w") as f:
    f.write(data)

# Read CSV into DataFrame
df = pd.read_csv("students.csv")
df

      Name  Age  Score
0    Alice   23     90
1      Bob   25     85
2  Charlie   22     95

In [ ]:
import pandas as pd

data = """Game,Hours,Rating
PEAK, 91.5, 9/10
Terraria, 618.5, 10/10
Rocket League, 1552, 8.7/10
"""
with open("games.csv", "w") as f:
    f.write(data)

dg = pd.read_csv("games.csv")
dg

            Game   Hours   Rating
0           PEAK    91.5     9/10
1       Terraria   618.5    10/10
2  Rocket League  1552.0   8.7/10

✅ **Your Turn**: Create your own small CSV (3–5 rows) and read it into Pandas.

## 2. Exploring DataFrames

In [ ]:
# Look at the first rows
df.head()

      Name  Age  Score
0    Alice   23     90
1      Bob   25     85
2  Charlie   22     95

In [ ]:
# Info about columns and data types
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    3 non-null      object
 1   Age     3 non-null      int64
 2   Score   3 non-null      int64
dtypes: int64(2), object(1)
memory usage: 204.0+ bytes

In [ ]:
# Summary statistics
df.describe()

             Age  Score
count   3.000000    3.0
mean   23.333333   90.0
std     1.527525    5.0
min    22.000000   85.0
25%    22.500000   87.5
50%    23.000000   90.0
75%    24.000000   92.5
max    25.000000   95.0

✅ **Your Turn**: Use `.head()` to preview your dataset and `.describe()` to see basic statistics.

In [ ]:
dg.head()
dg.describe()

             Hours
count     3.000000
mean    754.000000
std     739.618314
min      91.500000
25%     355.000000
50%     618.500000
75%    1085.250000
max    1552.000000

## 3. Writing CSV Files

In [ ]:
# Save the DataFrame to a new CSV
df.to_csv("students_copy.csv", index=False)
%ls *.csv

games.csv  students_copy.csv  students.csv

✅ **Your Turn**: Save your DataFrame to a CSV file called `my_data.csv`.

In [ ]:
dg.to_csv("games_copy.csv", index=False)
%ls *.csv

games_copy.csv  games.csv  students_copy.csv  students.csv

## 4. Reading Excel Files

In [ ]:
# Optional: Requires 'openpyxl' installed
# Save to Excel
df.to_excel("students.xlsx", index=False)

# Read Excel file
pd.read_excel("students.xlsx")

      Name  Age  Score
0    Alice   23     90
1      Bob   25     85
2  Charlie   22     95

✅ **Your Turn**: Try saving your dataset to Excel and reading it back (if supported in your environment).

In [ ]:
dg.to_excel("games.xlsx", index=False)

pd.read_excel("games.xlsx")

            Game   Hours   Rating
0           PEAK    91.5     9/10
1       Terraria   618.5    10/10
2  Rocket League  1552.0   8.7/10

---
### Summary
- `pd.read_csv` loads data into a DataFrame.
- Use `.head()`, `.info()`, `.describe()` to explore quickly.
- `df.to_csv` and `df.to_excel` save results.
- Pandas makes file I/O simple and reliable.