<a href="https://colab.research.google.com/github/jrpickens/data-science-notebooks/blob/main/6/James_Pickens_05_basic_cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

James Pickens

# 🧼 Cleaning Dirty Data (Missing Values & Type Fixes)

## 🔹 LEARNING GOALS:
- Detect and count missing values (`NaN`)
- Fill or drop missing data
- Convert column data types safely
- Understand the difference between `NaN`, `None`, `""`, and type mismatches

### 🧪 1. Load a Messy Dataset

In [ ]:
import pandas as pd
import numpy as np

data = {
    "Name": ["Alice", "Bob", "Charlie", "David", None],
    "Age": ["25", "thirty", 35, np.nan, "40"],
    "Signup Date": ["2022-01-01", "not a date", "2022/03/01", None, "April 5, 2022"],
    "Score": [95.5, None, 88.0, 92.5, ""],
    "Remarks": [None, "good", "", "late signup", None]
}

df = pd.DataFrame(data)
df

      Name     Age    Signup Date Score      Remarks
0    Alice      25     2022-01-01  95.5         None
1      Bob  thirty     not a date  None         good
2  Charlie      35     2022/03/01  88.0
3    David     NaN           None  92.5  late signup
4     None      40  April 5, 2022               None

### 🧯 2. Detecting Missing or Broken Values

In [ ]:
df.isnull()

    Name    Age  Signup Date  Score
0  False  False        False  False
1  False  False        False   True
2  False  False        False  False
3  False   True         True  False
4   True  False        False  False

In [ ]:
df.isnull().sum()

Name           1
Age            1
Signup Date    1
Score          1
dtype: int64

In [ ]:
df[df.isnull().any(axis=1)]

    Name     Age    Signup Date Score
1    Bob  thirty     not a date  None
3  David     NaN           None  92.5
4   None      40  April 5, 2022

### 🧹 3. Cleaning Strategy Options

In [ ]:
df.fillna({
    "Name": "Unknown",
    "Age": -1,
    "Signup Date": "1970-01-01",
    "Score": 0.0
})

      Name     Age    Signup Date Score
0    Alice      25     2022-01-01  95.5
1      Bob  thirty     not a date   0.0
2  Charlie      35     2022/03/01  88.0
3    David      -1     1970-01-01  92.5
4  Unknown      40  April 5, 2022

In [ ]:
df.dropna()

      Name Age Signup Date Score
0    Alice  25  2022-01-01  95.5
2  Charlie  35  2022/03/01  88.0

### 🧬 4. Data Type Fixes

In [ ]:
df.dtypes

Name           object
Age            object
Signup Date    object
Score          object
dtype: object

In [ ]:
df["Age"] = pd.to_numeric(df["Age"], errors="coerce")
df["Score"] = pd.to_numeric(df["Score"], errors="coerce")
df["Signup Date"] = pd.to_datetime(df["Signup Date"], errors="coerce")
df.dtypes

Name                   object
Age                   float64
Signup Date    datetime64[ns]
Score                 float64
dtype: object

### 🩹 5. Impute (Fill In) Fixed Missing Values

In [ ]:
df["Age"].fillna(df["Age"].median(), inplace=True)
df["Score"].fillna(df["Score"].mean())

0    95.5
1    92.0
2    88.0
3    92.5
4    92.0
Name: Score, dtype: float64

In [ ]:
df["Signup Date"].fillna(df["Signup Date"].min())

0   2022-01-01
1   2022-01-01
2   2022-01-01
3   2022-01-01
4   2022-01-01
Name: Signup Date, dtype: datetime64[ns]

In [ ]:
df["Name"].fillna("Unknown")

0      Alice
1        Bob
2    Charlie
3      David
4    Unknown
Name: Name, dtype: object

### 🤓 6. Cleaned Data Review

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Name         5 non-null      object
 1   Age          0 non-null      float64
 2   Signup Date  5 non-null      datetime64[ns]
 3   Score        5 non-null      float64
dtypes: datetime64[ns](1), float64(2), object(1)
memory usage: 292.0+ bytes

In [ ]:
df.describe(include="all")

         Name  Age          Signup Date     Score
count       5  0.0                    5   5.00000
unique      5  NaN                  NaN       NaN
top     Alice  NaN                  NaN       NaN
freq        1  NaN                  NaN       NaN
mean      NaN  NaN  2022-01-01 00:00:00  92.00000
min       NaN  NaN  2022-01-01 00:00:00  88.00000
25%       NaN  NaN  2022-01-01 00:00:00  92.00000
50%       NaN  NaN  2022-01-01 00:00:00  92.00000
75%       NaN  NaN  2022-01-01 00:00:00  92.50000
max       NaN  NaN  2022-01-01 00:00:00  95.50000
std       NaN  NaN                  NaN   2.66927

### 🧪 Try It Yourself

Modify the `data` dictionary at the top of this notebook. Add:
- A new column with some `None` and `""` values
- At least one row with all columns filled incorrectly
Then re-run the notebook and fix it step-by-step.

In [ ]:
df = pd.DataFrame(data)

df['Name'] = df['Name'].fillna('Unknown')

df['Age'] = pd.to_numeric(df['Age'], errors='coerce')
df['Age'] = df['Age'].fillna(df['Age'].median())

df['Signup Date'] = pd.to_datetime(df['Signup Date'], errors='coerce')
df['Signup Date'] = df['Signup Date'].fillna(df['Signup Date'].min())

df['Score'] = pd.to_numeric(df['Score'], errors='coerce')
df['Score'] = df['Score'].fillna(df['Score'].mean())

df['Remarks'] = df['Remarks'].replace("", np.nan)
df['Remarks'] = df['Remarks'].fillna("No Remarks")

df

      Name   Age Signup Date  Score      Remarks
0    Alice  25.0  2022-01-01   95.5   No Remarks
1      Bob  35.0  2022-01-01   92.0         good
2  Charlie  35.0  2022-01-01   88.0   No Remarks
3    David  35.0  2022-01-01   92.5  late signup
4  Unknown  40.0  2022-01-01   92.0   No Remarks

### 🧠 Mini-Challenge

> 🗂 Load `"data/survey.csv"` and:
- Identify which columns have missing values
- Use `.isnull().sum()` to get a null report
- Use a mix of `.fillna()`, `.dropna()`, and `pd.to_numeric()` or `pd.to_datetime()` to clean it
- Print a summary with `.info()` and `.describe()`

### 📝 Summary

| Concept        | Tool/Function                      |
|----------------|------------------------------------|
| Detect nulls   | `df.isnull()`, `df.isnull().sum()` |
| Drop rows      | `df.dropna()`                      |
| Fill values    | `df.fillna()`                      |
| Convert types  | `pd.to_numeric()`, `pd.to_datetime()` |
| Replace values | `df.replace()`                     |